name: viewing_nz
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  collection: ^1.19.1
  flutter_svg: ^2.1.0
  gap: ^3.0.1
  go_router: ^15.1.2
  chat_bubbles: ^1.7.0
  # solar_icons: ^0.0.5
  cached_network_image: ^3.4.1
  intl: ^0.20.2
  google_maps_flutter: ^2.12.2
  readmore: ^3.0.0
  flutter_rating_bar: ^4.0.1
  fl_chart: ^1.0.0
  url_launcher: ^6.3.1
  syncfusion_flutter_sliders: ^29.2.11
  calendar_date_picker2: ^2.0.1
  toastification: ^3.0.3
  carousel_slider: ^5.1.1
  photo_view: ^0.15.0
  flutter_chat_ui: ^2.5.2
  image_picker: ^1.1.2
  file_picker: ^10.2.0
  uuid: ^4.5.1
  flutter_chat_core: ^2.6.1
  device_preview: ^1.2.0
  keyboard_dismisser: ^3.0.0
  syncfusion_flutter_core: ^29.2.11
  flutter_chat_types: ^3.6.2
  auto_size_text: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

dependency_overrides:
  freezed_annotation: ^3.0.0
  provider: ^6.1.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/solar_icons/
    - assets/fonts/

  fonts:
    - family: Onest
      fonts:
        - asset: assets/fonts/Onest-Regular.ttf
        - asset: assets/fonts/Onest-Bold.ttf
          weight: 700
